{% set name = "gitui" %}
{% set version = "0.26.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/extrawurst/gitui/archive/v{{ version }}.tar.gz
  sha256: c69eccba2457c53c18b933794aa4ff3dfecb71af42349282108354d543e4d956

build:
  number: 0
  ignore_run_exports:
    - openssl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - make
    - perl  # [win]
    - cargo-bundle-licenses
  host:
    - openssl

test:
  commands:
    - gitui --help

about:
  home: https://github.com/extrawurst/gitui
  summary: 'blazing fast terminal-ui for git'
  description: 'Blazing 💥 fast terminal-ui for git written in rust 🦀'
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.md
  dev_url: https://github.com/extrawurst/gitui

extra:
  recipe-maintainers:
    - TheBlackSheep3
